### ISSUE TITLE
Provide automated updates for all commands downloading from github releases

### ISSUE THREAD

**Issue by jakzal** [jakzal/toolbox#332]
Currently only PHAR downloads are supported, which means regular file downloads won't be automatically updated (like https://github.com/jakzal/toolbox/pull/331).

**Comment by atrakic** [comment]
I wanted to give it a try with latest composer image:
 
```bash-5.1# curl -s https://api.github.com/repos/jakzal/toolbox/releases/latest \
  | grep "browser_download_url.*toolbox.phar" \
  | cut -d '"' -f 4 \
  | xargs curl -Ls -o toolbox \
  && chmod +x toolbox
bash-5.1# ./toolbox 
toolbox dev

Usage:
  command [options] [arguments]


Fatal error: Uncaught Error: Class "Normalizer" not found in phar:///usr/src/myapp/toolbox/vendor/symfony/console/Helper/Helper.php:46
Stack trace:
#0 phar:///usr/src/myapp/toolbox/vendor/symfony/console/Descriptor/TextDescriptor.php(278): _HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Helper\Helper::strlen('h')
#1 phar:///usr/src/myapp/toolbox/vendor/symfony/console/Descriptor/TextDescriptor.php(85): _HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Descriptor\TextDescriptor->calculateTotalWidthForOptions(Array)
#2 phar:///usr/src/myapp/toolbox/vendor/symfony/console/Descriptor/TextDescriptor.php(169): _HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Descriptor\TextDescriptor->describeInputDefinition(Object(_HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Input\InputDefinition), Array)
#3 phar:///usr/src/myapp/toolbox/vendor/symfony/console/Descriptor/Descriptor.php(51): _HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Descriptor\TextDescriptor->describeApplication(Object(_HumbugBoxdf9a73bfc3f8\Zalas\Toolbox\Cli\Application), Array)
#4 phar:///usr/src/myapp/toolbox/vendor/symfony/console/Helper/DescriptorHelper.php(51): _HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Descriptor\Descriptor->describe(Object(_HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Output\ConsoleOutput), Object(_HumbugBoxdf9a73bfc3f8\Zalas\Toolbox\Cli\Application), Array)
#5 phar:///usr/src/myapp/toolbox/vendor/symfony/console/Command/ListCommand.php(55): _HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Helper\DescriptorHelper->describe(Object(_HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Output\ConsoleOutput), Object(_HumbugBoxdf9a73bfc3f8\Zalas\Toolbox\Cli\Application), Array)
#6 phar:///usr/src/myapp/toolbox/vendor/symfony/console/Command/Command.php(228): _HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Command\ListCommand->execute(Object(_HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Input\ArgvInput), Object(_HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///usr/src/myapp/toolbox/vendor/symfony/console/Application.php(826): _HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Command\Command->run(Object(_HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Input\ArgvInput), Object(_HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///usr/src/myapp/toolbox/vendor/symfony/console/Application.php(251): _HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Application->doRunCommand(Object(_HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Command\ListCommand), Object(_HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Input\ArgvInput), Object(_HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///usr/src/myapp/toolbox/src/Cli/Application.php(29): _HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Application->doRun(Object(_HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Input\ArgvInput), Object(_HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///usr/src/myapp/toolbox/vendor/symfony/console/Application.php(152): _HumbugBoxdf9a73bfc3f8\Zalas\Toolbox\Cli\Application->doRun(Object(_HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Input\ArgvInput), Object(_HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Output\ConsoleOutput))
#11 phar:///usr/src/myapp/toolbox/bin/toolbox.php(6): _HumbugBoxdf9a73bfc3f8\Symfony\Component\Console\Application->run()
#12 /usr/src/myapp/toolbox(12): require('phar:///usr/src...')
#13 {main}
  thrown in phar:///usr/src/myapp/toolbox/vendor/symfony/console/Helper/Helper.php on line 46
bash-5.1# php -v
PHP 8.0.6 (cli) (built: May  7 2021 20:48:50) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.6, Copyright (c) Zend Technologies
docker run -it --rm --name my-running-script -v "$PWD":/usr/src/myapp -w /usr/src/myapp composer:latest bash
```

**Comment by jakzal** [comment]
@atrakic I'm not sure what you're trying to do.

**Comment by atrakic** [comment]
@jakzal I have existing symfony project that I mount with `composer:latest` and I was thinking to use your toolbox and to tests stuff with, but it fails

**Comment by jakzal** [comment]
@atrakic I see, so it's unrelated to the issue you're commenting on. Can you please create a new issue and provide as much detail as you can?
